baseurl = "https://greatsilence.github.io/" # Controls base URL sitewide
languageCode = "en-US" # Controls site language
title = "After Dark" # Homepage title and page title suffix
pagination.pagerSize = 11 # Number of posts to show before paginating
copyright = "Copyright &copy; 2025 Matthias Fuchs. Licensed under <a target=\"_blank\" rel=\"external noopener license\" href=\"https://creativecommons.org/licenses/by-nd/4.0/\">CC-BY-ND-4.0</a>." # Optional, remove to suppress copyright notices

# Controls default theme and theme components
theme = [
  "fractal-forest", # OBSD
  "after-dark" # AGPL-3.0-or-later
]

disableLiveReload = false # Optional, set true to disable live reload
enableRobotsTXT = true # Suggested, enable robots.txt file
sectionPagesMenu = "main" # Enable menu system for lazy bloggers

[markup.goldmark.renderer]
  unsafe = true # Optional, allows HTML inside your CommonMark content
[markup.tableOfContents]
  startLevel = 1 # Suggested, draws TOC using all heading levels
  endLevel = 6 # Suggested, draws TOC using all heading levels
[markup.highlight]
  noClasses = false # Suggested, used for custom syntax highlighting

[params]
  description = "Blog about everything I love" # Suggested, controls default description meta
  author = "Matthias Fuchs" # Optional, controls author name display on posts
  hide_author = false # Optional, set true to hide author name on posts
  disable_csp = false # Optional, set true to disable content security policy
  coverImage = [
    "/images/purple-gnu.jpg"
   ] # Suggested, controls default Open Graph images


[params.layout.menu.main]
  hidden = false # Optional, set false or remove to show section menu

[params.layout.footer]
  hidden = false # Optional, set true to hide footer

[params.modules.fractal_forest]
  enabled = true # Optional, set false to disable module
  decoders = ["bpgdec8a"] # Optional, 8-bit javascript decoder with animation


[outputs]
  home = ["HTML", "RSS", "JSON"]

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Posts"
  weight = 2
  identifier = "post"
  url = "/post/"

